### ISSUE TITLE
parameter settings

### ISSUE THREAD

**Issue by LittleYuanzi** [open-mmlab/OpenLidarPerceptron#105]
Hello, I have a question for you. Now I want to train the data of my own autonomous driving scene (360 degree with 128 line radar). Compared with KITTI, this data set is closer to the waymo dataset. When using PvRCNN, what parameters should I adjust to improve the detection performance. Or will you add waymo to the project. thank you very much!

**Comment by sshaoshuai** [comment]
For training with 360 degrees, you just need to set a proper dataset config for your own dataset, such as you should set `POINT_CLOUD_RANGE` as a 360 degree range, and also set a proper `VOXLE_SIZE` to ensure your GPU memory is ok. The waymo setting of PV-RCNN is mentioned in the paper, you could refer to our paper. 
We will release the waymo dataset to this project soon.

**Comment by LittleYuanzi** [comment]
thank you very much!
