### ISSUE TITLE
why a customized DistributedSampler is needed?

### ISSUE THREAD

**Issue by toyot-li** [open-mmlab/OpenLidarPerceptron#1119]
@sshaoshuai Hello, I wonder what is the motivation for redefining a `DistributedSampler` [here](https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/datasets/__init__.py#L27), whose `__iter__` method is pretty similar to the PyTorch built-in DistributedSampler, as shown in the PyTorch source code https://pytorch.org/docs/stable/_modules/torch/utils/data/distributed.html#DistributedSampler
In addition, if the tail indices are duplicated ones, would the whole evaluation process be correct? Thanks.

**Comment by sshaoshuai** [comment]
Thanks for pointing out this problem. 
It is some legacy codes in the early stage of OpenPCDet, and I guess we do not need it anymore. But for safety reason, we still keep it now. Maybe we will remove it after checking the correctness of this part.

**Comment by sshaoshuai** [comment]
For the issue of duplicated ones, I do not notice this part. Can you provide more details?

**Comment by sshaoshuai** [comment]
The duplicated samples will be clipped in the merging process, please refer to here: https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/utils/common_utils.py#L230
