### ISSUE TITLE
when use train kitti train pillarnet.yaml. KeyError:'finalbox_dicts'

### ISSUE THREAD

**Issue by keyMrZ** [open-mmlab/OpenLidarPerceptron#1605]
openpcdet使用pillarnet. yaml训练后eval报错finalpred_dict=batch_dict['finalboxdicts']KeyError:'finalbox_dicts'我也有这个问题，请问有解决办法吗

**Comment by OpenReviewCode** [comment]
把 post_processing 函数注释掉
