### ISSUE TITLE
questions about GETTING_STARTED.md

### ISSUE THREAD

**Issue by NayaBaslan** [open-mmlab/OpenLidarPerceptron#1630]
I would like to start using OpenPCDet with the Waymo dataset.

Could you please provide more information about the data format that is needed.

I have successfully ran the library installation with all the dependecies as instructed in `INSTALL.md` using

`python setup.py develop`

Can you provide some more explanation about the Waymo setup under ` GETTING_STARTED.md`

In the Path `OpenPCDet/data/waymo/ImageSets` I have train.txt with the following:
```segment-10017090168044687777_6380_000_6400_000_with_camera_labels.tfrecord
segment-10023947602400723454_1120_000_1140_000_with_camera_labels.tfrecord
segment-1005081002024129653_5313_150_5333_150_with_camera_labels.tfrecord
segment-10061305430875486848_1080_000_1100_000_with_camera_labels.tfrecord
segment-10072140764565668044_4060_000_4080_000_with_camera_labels.tfrecord
....
```

And as the instructions say, I have to download the these waymo tfrecords into the `raw_data` folder.

However, I cannot find anything of this format.

Can you please tell me how to obtain this data. The Waymo dataset has both the Perception and the Motion dataset. Which one should be used in this case? 
The only data I am to download from Waymo is of this form

`uncompressed_scenario_training_training.tfrecord-00001-of-01000`

but then when running 

```# only for single-frame setting
python -m pcdet.datasets.waymo.waymo_dataset --func create_waymo_infos \
    --cfg_file tools/cfgs/dataset_configs/waymo_dataset.yaml
```

I get all the errors that the segments could not be found.

```NotFoundError: .../OpenPCDet/data/waymo/raw_data/segment-12866817684252793621_480_000_500_000_with_camera_labels.tfrecord
NotFoundError: .../OpenPCDet/data/waymo/raw_data/segment-11616035176233595745_3548_820_3568_820_with_camera_labels.tfrecord
NotFoundError: .../OpenPCDet/data/waymo/raw_data/segment-13184115878756336167_1354_000_1374_000_with_camera_labels.tfrecord
NotFoundError: .../OpenPCDet/data/waymo/raw_data/segment-1331771191699435763_440_000_460_000_with_camera_labels.tfrecord
NotFoundError: .../OpenPCDet/data/waymo/raw_data/segment-13941626351027979229_3363_930_3383_930_with_camera_labels.tfrecord
NotFoundError: .../OpenPCDet/data/waymo/raw_data/segment-1405149198253600237_160_000_180_000_with_camera_labels.tfrecord
```

**Comment by kmodexc** [comment]
I think you need the perception dataset v1.4.3 . If you look at individial files go to training you see exactly these files as they expect it. I guess they are the same files at these archives.
