### ISSUE TITLE
Question about adam_onecycle optimizer

### ISSUE THREAD

**Issue by junha-l** [open-mmlab/OpenLidarPerceptron#1635]
Hi, 

I'm currently using a custom `adam_onecycle` optimizer implemented in this codebase, with `true_wd=True` and `bn_wd=True`, along with its associated scheduler. However, I've noticed that PyTorch provides `AdamW` optimizer and `OneCycleLR` scheduler, which seem to have similar functionality.

I ran some experiments switching between custom `adam_onecycle` and PyTorch's implementation, and I noticed significant performance differences.

Could you help me in understanding the main differences between:

1. custom `adam_onecycle` optimizer (with `true_wd=True, bn_wd=True`) + its scheduler
2. PyTorch's `AdamW` + `OneCycleLR` scheduler

Specifically, I'm interested in understanding what might be causing the performance differences I observed.

Thanks!

**Comment by bollossom** [comment]
> Hi,
> 
> I'm currently using a custom `adam_onecycle` optimizer implemented in this codebase, with `true_wd=True` and `bn_wd=True`, along with its associated scheduler. However, I've noticed that PyTorch provides `AdamW` optimizer and `OneCycleLR` scheduler, which seem to have similar functionality.
> 
> I ran some experiments switching between custom `adam_onecycle` and PyTorch's implementation, and I noticed significant performance differences.
> 
> Could you help me in understanding the main differences between:
> 
> 1. custom `adam_onecycle` optimizer (with `true_wd=True, bn_wd=True`) + its scheduler
> 2. PyTorch's `AdamW` + `OneCycleLR` scheduler
> 
> Specifically, I'm interested in understanding what might be causing the performance differences I observed.
> 
> Thanks!

Does adamw perform better than adam? How much better?
