### ISSUE TITLE
Floating Point Exception 

### ISSUE THREAD

**Issue by jyothsna-phd22** [open-mmlab/OpenLidarPerceptron#1642]
Hi,

While I was training any model on kitti dataset, I am getting floating point exception at epoch 0 and terminated training. How to resolve this issue??

Kindly help me....

**Comment by beijbom** [comment]
Same here. I am training `cfgs/nuscenes_models/cbgs_pp_multihead.yaml` on the nuScenes mini dataset. @jyothsna-phd22 : were you able to resolve the issue?

**Comment by beijbom** [comment]
Tracked down the offending call. It's `tv.from_numpy(points)` on this line: https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/datasets/processor/data_processor.py#L55.

**Comment by jyothsna-phd22** [comment]
Where should we change in this line??

**Comment by beijbom** [comment]
I don't yet know how to fix it. I was just sharing that it seems to be the offending line.

**Comment by beijbom** [comment]
On digging further, it seems this is due to a mismatch between the binaries of the spconv library and the rest of the environment. I got it to run using the dockerfile in this PR: https://github.com/open-mmlab/OpenPCDet/pull/1648

**Comment by Sun-Cold** [comment]
Same issue here，this is my env info：
python    3.10.14
CUDA     12.1
numpy    2.0.1
spconv-cu120    2.3.6
Here is my solution for reference: downgrade numpy version to 1.26.4
`conda install numpy=1.26.4`

**Comment by likecaulfield** [comment]
> Same issue here，this is my env info： python 3.10.14 CUDA 12.1 numpy 2.0.1 spconv-cu120 2.3.6 Here is my solution for reference: downgrade numpy version to 1.26.4 `conda install numpy=1.26.4`

It worked for me too thank you!
