### ISSUE TITLE
Custom Dataset npy file demo.py 

### ISSUE THREAD

**Issue by jyothsna-phd22** [open-mmlab/OpenLidarPerceptron#1647]
Hi,

I have my own custom point cloud dataset with .npy file with contents x,y,z,intensity.  When I give my .npy file to run on a pretrained model like this,
"python demo.py --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt pv_rcnn_8369.pth  --data_path  /home/OpenPCdet/tools/data.npy"

It is opening the open3d visualizer but not showing npy file contents also. But when I view the npy file separately, I am able to visualize .npy data. KIndly help me in visualizing the predictions of my custom data.  The sample contents of my data.npy is as follows:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<body link="#0563C1" vlink="#954F72">

37.9439 | -0.00628 | -2.466 | 0.035294
26.7708 | -0.00876 | -2.39724 | 0.015686
20.2794 | -0.01343 | -2.31234 | 0.015686
16.1137 | -0.00762 | -2.23378 | 0.015686
13.3748 | -0.00612 | -2.18284 | 0.019608
1.88224 | 0.000145 | -0.35099 | 0.015686
1.53985 | 0.000332 | -0.32423 | 0.043137
1.36061 | 0.000429 | -0.31915 | 0.039216
1.22907 | 0.000289 | -0.31763 | 0.047059
1.1378 | 0.000159 | -0.32153 | 0.039216
1.02137 | 0.00079 | -0.31302 | 0.043137
0.966726 | 0.000644 | -0.31948 | 0.031373
0.882442 | 0.00069 | -0.3122 | 0.015686
0.851218 | 0.000707 | -0.32154 | 0.003922
19.3286 | -0.1246 | 7.30944 | 0.094118
19.2978 | -0.1244 | 6.82069 | 0.117647
19.2955 | -0.12775 | 6.35392 | 0.121569
19.2769 | -0.12426 | 5.86679 | 0.066667
0 | 0 | 0 | 0
0 | 0 | 0 | 0
0 | 0 | 0 | 0
0 | 0 | 0 | 0
0 | 0 | 0 | 0
0 | 0 | 0 | 0
44.8352 | -0.28275 | 4.80573 | 0.027451
44.7239 | -0.28985 | 3.69147 | 0.023529

</body>

</html>

**Comment by thanhpt93** [comment]
Did you fix the bug?
I see your x,y,z coordinate values ​​are strange
In my tests, these values ​​cannot be that small
