### ISSUE TITLE
nuscenes_dataset process

### ISSUE THREAD

**Issue by shingszelam** [open-mmlab/OpenLidarPerceptron#1650]
Please, why do I use the instruction:
**python -m pcdet.datasets.nuscenes.nuscenes_dataset --func create_nuscenes_infos \
    --cfg_file tools/cfgs/dataset_configs/nuscenes_dataset.yaml \
    --version v1.0-trainval**
No gt_database and nuscenes_dbinfos_10sweeps_withvelo.pkl are generated
======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 29.8 seconds.
======
Reverse indexing ...
Done reverse indexing in 9.8 seconds.
======
total scene num: 850
exist scene num: 850
v1.0-trainval: train scene(700), val scene(150)
create_info: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 34149/34149 [08:06<00:00, 70.14it/s]
train sample: 28130, val sample: 6019
2024-08-17 17:12:40,591   INFO  Loading NuScenes dataset
2024-08-17 17:12:40,591   INFO  Total samples for NuScenes dataset: 0
0it [00:00, ?it/s]

**Comment by kipperjjang** [comment]
Hello. Did you solve the problem? If you did, could you tell me how you did?
