### ISSUE TITLE
Question about rotation

### ISSUE THREAD

**Issue by ShelbyXu9** [open-mmlab/OpenLidarPerceptron#1654]
i have a question about rotate points along Z axis, in OpenPCDet code, rotation matrix is following, i wonder if sina and -sina should change its location?
![image](https://github.com/user-attachments/assets/fdc2644c-5dad-46e0-943c-e164ac6ff4cb)

**Comment by ShelbyXu9** [comment]
but i use some examples to check, the OpenPCDet code is correct, anyone could tell me why?

**Comment by wangziyi2016** [comment]
They use points@R instead of R@points, resulting in the matrix being transposed.

**Comment by ShelbyXu9** [comment]
> They use points@R instead of R@points, resulting in the matrix being transposed.

oh, yes. I got it now. Thanks, ziyi.
