### ISSUE TITLE
Any ROS2 package for OpenPcdet?

### ISSUE THREAD

**Issue by aatefi2** [open-mmlab/OpenLidarPerceptron#1656]
Hi,

I have been using OpenPCDet (https://github.com/open-mmlab/OpenPCDet) for 3D object detection on LiDAR data. I found some GitHub repositories that provide ROS packages for OpenPCDet, and I'm wondering if there is a ROS2 package available for this purpose.

I appreciate any help in advance.
Abbas

**Comment by Petros626** [comment]
On reddit nobody replied to your question, so I only found the pcdet_ros2 package, which link is down. 

Update: I contacted the author: https://bitbucket.org/pradhanshrijal/pcdet_ros2/src/main/

@aatefi2 close if solved for you.

**Comment by aatefi2** [comment]
Hi Petros626, 

Thank you for your help. Yes, it works for me.
