### ISSUE TITLE
Confusion matrix 

### ISSUE THREAD

**Issue by jyothsna-phd22** [open-mmlab/OpenLidarPerceptron#1665]
Hi,
Is there code base for confusion matrix???

**Comment by Petros626** [comment]
Did the codebase contained any methods for it?

**Comment by binshaea** [comment]
Hi, I have the same question and I already went through the code
I am using PV-RCNN model for training with custom dataset and I could not find a code that computes confusion matrix or model accuracy. if anyone can confirm this or is there a similar code for these metrics in the other models provided by OpenPCDet?

**Comment by Petros626** [comment]
I mean my question was more like, did you searched all the code for a hint. I couldn't find anything that would fit a confusion matrix.

![image](https://github.com/user-attachments/assets/dba3c26f-fb92-4990-a692-495a4ee0eee1)

**Comment by Petros626** [comment]
@binshaea when you didn't found anything in the code base, please close this issue.
