### ISSUE TITLE
demo.py: error: unrecognized arguments

### ISSUE THREAD

**Issue by little-win** [open-mmlab/OpenLidarPerceptron#1666]
when i want to use the demo to deal with my data, it failed
root@autodl-container-b0a041be91-e7140047:~/OpenPCDet/tools# python3 demo.py --cfg_file cfgs/kitti_models/pv_rcnn.yaml \ --ckpt pv_rcnn_8369.pth \ --data_path 000030g.npy
usage: demo.py [-h] [--cfg_file CFG_FILE] [--data_path DATA_PATH] [--ckpt CKPT] [--ext EXT]
demo.py: error: unrecognized arguments:  --ckpt pv_rcnn_8369.pth  --data_path 000030g.npy
and the things are in the tools
<img width="122" alt="image" src="https://github.com/user-attachments/assets/734c70d3-0b9e-4265-9e6e-15ca08a154d9">
![屏幕截图 2024-09-16 085111](https://github.com/user-attachments/assets/0a27f8f1-67a8-45ca-b1fb-f87ace664bf0)

**Comment by little-win** [comment]
some ones here？

**Comment by Petros626** [comment]
I think this repo isn't maintained anymore. Everything must be figured out on our own and with the old issues.

**Comment by little-win** [comment]
python3 demo.py --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt pv_rcnn_8369.pth --data_path 000030g.npy
it should remove the '\' between the path, it work, but i need to solve other question.

**Comment by little-win** [comment]
done
