### ISSUE TITLE
PillarNet different pillar sizes

### ISSUE THREAD

**Issue by ahmedius2** [open-mmlab/OpenLidarPerceptron#1667]
Hi, thanks for making this wonderful work publicly available. I am trying to train Pillarnet with different pillar sizes as explained in their paper. It is not clear to me how to detach a subset of the backbone convolutions when increasing the pillar size. The number of output channels needs to be changed I guess. Could anyone please provide the configuration files for pillar sizes 0.15, 0.3, and 0.6 and what needs to be updated in the code?

**Comment by Petros626** [comment]
Try to find in the code the specific area where the pillar size is calculated or set. You can follow this rule: changes in .yaml file should be verified in the code.

Start here and dig further: https://github.com/open-mmlab/OpenPCDet/blob/8cacccec11db6f59bf6934600c9a175dae254806/pcdet/models/detectors/pillarnet.py#L4
