### ISSUE TITLE
error:python setup.py develop

### ISSUE THREAD

**Issue by zscya** [open-mmlab/OpenLidarPerceptron#1668]
But the cuda I installed is 11.1 version, including the setting of environment variables is also 11.1 version, I do not know why it can not find cuda12.2 error
![2024-09-24 11-20-24屏幕截图](https://github.com/user-attachments/assets/21f9dde7-44c0-451d-94c5-59af5260d6e9)
![2024-09-24 11-23-12屏幕截图](https://github.com/user-attachments/assets/eb24323d-4a38-40f6-82c2-0b8342334547)
![2024-09-24 11-24-07屏幕截图](https://github.com/user-attachments/assets/f8e18b28-b6d5-4777-93ae-4423a69d58ee)
![2024-09-24 11-29-03屏幕截图](https://github.com/user-attachments/assets/80dbacbc-d23a-41d1-b039-a851241240dd)
![2024-09-24 11-28-53屏幕截图](https://github.com/user-attachments/assets/2e736c54-9e81-4e98-91f6-9f68179d8f6a)
![2024-09-24 11-28-40屏幕截图](https://github.com/user-attachments/assets/db3a915f-eb3c-450d-972d-0b44d2da4121)

**Comment by zscya** [comment]
can you help me?thank you,you will get many papers in you future

**Comment by Petros626** [comment]
Hey, did you checked that your CUDA-Version is compatible with the spconv library? In my case I did the following for a clean installation, maybe it helps you


`conda activate openpcdet`

PyTorch 2: `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118` (**look here for your cuda version**)

CUDA 11.8:  installed via runfile from the official nvidia homepage (let the new nvidia-driver as it is)

spconv: `pip install spconv-cu118`

`git clone https://github.com/open-mmlab/OpenPCDet.git`
`cd OpenPCDet`

`pip install -r requirements.txt` **(here you must add the following: av2==0.2.0 and kornia==0.6.5)**

`python setup.py develop`
`python demo.py --cfg_file /home/rlab10/OpenPCDet/tools/cfgs/kitti_models/pointpillar.yaml --ckpt /home/rlab10/OpenPCDet/pointpillar_7728.pth --data_path /home/rlab10/OpenPCDet/data/kitti/000006.bin` 

**(I've downloaded the `.pth` and one `.bin` example)**

**Comment by zscya** [comment]
thank you,i have solve it

**Comment by Petros626** [comment]
@zscya no problem, please close the issue.
