### ISSUE TITLE
Problem encountered in generating data format pkl

### ISSUE THREAD

**Issue by MAI-KOKO** [open-mmlab/OpenLidarPerceptron#1670]
When I run this instaruction : python -m pcdet.datasets.kitti.kitti_dataset create_kitti_infos tools/cfgs/dataset_configs/kitti_dataset.yaml  
RuntimeWarning: 'pcdet.datasets.kitti.kitti_dataset' found in sys.modules after import of package 'pcdet.datasets.kitti', but prior to execution of 'pcdet.datasets.kitti.kitti_dataset';

**Comment by Petros626** [comment]
Maybe in a few days/weeks I can help you, because I'm also working with KITTI

**Comment by Petros626** [comment]
@MAI-KOKO you can ignore it it's just a warning caused by the method calling the function of everything runs normally it's no issue
