### ISSUE TITLE
How do I submit a model trained with pcdet to Kitti for evaluation?

### ISSUE THREAD

**Issue by shingszelam** [open-mmlab/OpenLidarPerceptron#1672]
I trained a model and wanted to see the results on the test set, but I couldn't find the corresponding file to submit to Kitti. Can someone help me?

**Comment by Petros626** [comment]
some users mentioned that in the issues.

**Comment by shingszelam** [comment]
> some users mentioned that in the issues.

Is there a solution? I didn't see one.

**Comment by Petros626** [comment]
I've read it in the issues with keywords(test, eval, évaluation etc.) you will find it. I remember that user OrangeSodaHub wrote a custom evaluation function, but I never used it.

**Comment by shingszelam** [comment]
> (

Ok, thank you!!

**Comment by shingszelam** [comment]
> I've read it in the issues with keywords(test, eval, évaluation etc.) you will find it. I remember that user OrangeSodaHub wrote a custom evaluation function, but I never used it.

ok,thank you!!

**Comment by Petros626** [comment]
@shingszelam please close this issue then.
