### ISSUE TITLE
nuScenes Model Download Links Broken

### ISSUE THREAD

**Issue by hongbozheng** [open-mmlab/OpenLidarPerceptron#1673]
Several download links for nuScenes models are not working. Can you fix those?
Thanks in advance!

**Comment by Petros626** [comment]
for me all links of the pretrained nuscenes models are working.

**Comment by hongbozheng** [comment]
> for me all links of the pretrained nuscenes models are working.

can you share me the working link for [CenterPoint (voxel_size=0.1)](https://github.com/open-mmlab/OpenPCDet/blob/master/tools/cfgs/nuscenes_models/cbgs_voxel01_res3d_centerpoint.yaml) model? Thanks!

**Comment by Petros626** [comment]
my bad except of this i tried all links, this could help: https://github.com/open-mmlab/mmdetection3d/tree/1.0/configs/centerpoint
