### ISSUE TITLE
Custom Dataset Labels

### ISSUE THREAD

**Issue by paureverte** [open-mmlab/OpenLidarPerceptron#1674]
Hello, 

I've been recently trying to set up a custom dataset from pointclouds gathered from a RSHelios16P (similar pattern to VLP16). This is for an agricultural project, in which the goal is use the 3D clouds to detect trees. 

As for what I understand from [CUSTOM_DATASET_TUTORIAL.md](https://github.com/open-mmlab/OpenPCDet/blob/master/docs/CUSTOM_DATASET_TUTORIAL.md), custom datasets are somehow treated as KITTI dataset, so this class mapping to KITTI classes needs to be done:
![image](https://github.com/user-attachments/assets/7023ac4b-98c1-4deb-82b6-ec700c687d3b)

Does this mean that only labels already defined in KITTI dataset can be used? What if I want to detect classes that are not specified in the KITTI dataset? 

Also, is there any available custom dataset adapter following the tutorial online? 

Thank you!

**Comment by Petros626** [comment]
For my understanding the custom dataset template relies on the kittidataset, so the classes were limited to these three. In the official labels there were more labels available, but for different reasons only the classical classes are used. When you try to detect trees with different classes, than you have to change all the classes in custom template and kittidataset. You can also search through the issues some people created tutorials for your case.
