### ISSUE TITLE
Inquiry for a new version of Dockerfile 

### ISSUE THREAD

**Issue by LiuStan99** [open-mmlab/OpenLidarPerceptron#1685]
Hi! 

I have built the docker image from the provided [Dockerfile with cuda11.6](https://github.com/open-mmlab/OpenPCDet/blob/master/docker/cu116.Dockerfile). Now I am trying to run models on an H100 GPU. But it seems the corresponding PyTorch version is not compatible with the CUDA capability. As shown below:

```
/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:155: UserWarning: 
NVIDIA H100 80GB HBM3 with CUDA capability sm_90 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75 sm_80 sm_86.
If you want to use the NVIDIA H100 80GB HBM3 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
```

Do we have a newer version of Dockerfile which is compatible? Thanks a lot in advance for the support!

**Comment by Petros626** [comment]
some users mentioned this problem in the issues.
