### ISSUE TITLE
PV-RCNN algorithm configuration environment

### ISSUE THREAD

**Issue by aaaddddddddddd** [open-mmlab/OpenLidarPerceptron#1688]
Would anyone like to share the versions of CUDA and Pytorch used to configure the environment using the PV-RCNN algorithm? Thank you very much

**Comment by Petros626** [comment]
did the description in https://github.com/open-mmlab/OpenPCDet/blob/master/docs/INSTALL.md didn't work for you? I've already posted a succesful installation in the issues.

I used:
PyTorch 2
CUDA 11.8
spconv-cu118
and updated requirements.txt

**Comment by aaaddddddddddd** [comment]
Thank you very much, I did not see this document before.




2020031776郭书迪
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/OpenPCDet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月3日(星期二) 下午5:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/OpenPCDet] PV-RCNN algorithm configuration environment (Issue #1688)





 
did the description in https://github.com/open-mmlab/OpenPCDet/blob/master/docs/INSTALL.md didn't work for you?

**Comment by Petros626** [comment]
@aaaddddddddddd please close this issue then.
