### ISSUE TITLE
FOV_POINTS_ONLY

### ISSUE THREAD

**Issue by soldierofhell** [open-mmlab/OpenLidarPerceptron#84]
Hi,

I noticed that all configs have "FOV_POINTS_ONLY: True". Also in SECOND paper it is stated: "Points that lie outside the camera view frustum need to be removed."

I don't understand this limitation. Is it really necessary? If not, does it affect performance of pretrained models for objects outside of FOV?

Regards,

**Comment by sshaoshuai** [comment]
The only reason the only using the FOV points is that KITTI dataset only provides annotations within the FOV area. For other datasets like Waymo/Nuscene, you do not need to remove the points outside the FOV.
