### ISSUE TITLE
How to reproduce the result of pedestrain and cyclist of PartA2

### ISSUE THREAD

**Issue by LZDSJTU** [open-mmlab/OpenLidarPerceptron#88]
Hi, shaoshuai. I can get similar result of the car category on the val set using PartA2. However, I cannot achieve the same result for pedestrain and cyclist as the table 6 and 13 in your paper.

Could you provide the training pipeline and the config for these two categories? And if I want to reproduce the similar result in the KITTI test set, what else do I need to do?

Thank you very much.

**Comment by sshaoshuai** [comment]
The PartA2 codes from PCDet have been largely refactored for better understanding, and we mainly focus on matching the performance of Car category. 
Actually the results of ped/cyc are not stable on the KITTI dataset, it may need be carefully tuned for the training/testing parameters. The cyclist performance of PartA2 from PCDet should be similar with the paper performance, but the pedestrian does need be further tuned.
