### ISSUE TITLE
what's the coordinate definitions of LiDAR and local in pcdet 2.0  ?

### ISSUE THREAD

**Issue by xzswater** [open-mmlab/OpenLidarPerceptron#95]
In pcdet 1.0，they are:

_We have the following definitions:
The LiDAR coordinate denotes the KITTI LiDAR coordinate system, with x: forward, y: left, z: up, and the direction of zero orientation is along the -y.
The local coordinate denotes the coordinate system of a object, with x: heading direction of this object, y: perpendicular to x, z: up, and the direction of zero orientation is along the x.
Hence, for transforming the LiDAR coordinate to local coordinate, we should rotate the object points with ry + np.pi / 2_

But in pcdet 2.0, i notice these differences:
![image](https://user-images.githubusercontent.com/52267702/85565329-9f5d5b80-b661-11ea-87a1-74328ecd0b5f.png)

**Comment by sshaoshuai** [comment]
Please refer to the following figure:

![image](https://user-images.githubusercontent.com/8805870/85573659-ac317d80-b668-11ea-97ee-0108ebc83e39.png)
