### ISSUE TITLE
Metric number in the table

### ISSUE THREAD

**Issue by buaaJeremyduan** [open-mmlab/OpenLidarPerceptron#97]
The Metric number in the table is evaluated by AP-11, is that right? Could you please put AP-40 numbner in the table too?

**Comment by Gus-Guo** [comment]
Yes. The metric numbers in the table are all evaluated by AP-11. Thanks for your advice and we will consider put more information in that table later. if you need it now, the corresponding models are provided and our evaluation codes support AP-40 evaluation. You can simply run the codes and obtain all the results including AP-11 and AP-40 on bev and 3d.

**Comment by buaaJeremyduan** [comment]
OK, Thanks for your information.
